name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git describe --tags

      - name: Install dependencies
        run: sudo apt-get install -y autoconf automake libtool

      - name: Configure project
        run: |
          libtoolize --copy
          autoreconf --install
          ./configure

      - name: Run clang-tidy
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''  # disable clang-format
          tidy-checks: '-*,bugprone-*,clang-analyzer-core.*,clang-analyzer-deadcode.*,clang-analyzer-nullability.*,clang-analyzer-security.FloatLoopCounter,clang-analyzer-unix.*,-clang-analyzer-security.insecureAPI.*'
          files-changed-only: ${{ github.event_name == 'pull_request' }}
          database: ''
          extra-args: '-I. -Isrc/lib -DHAVE_CONFIG_H'
          extensions: 'c'
          ignore: 'src/fsqd.c|src/test|src/benchmark'
          thread-comments: ${{ github.event_name == 'pull_request' }}
          step-summary: true
          file-annotations: true

      - name: Fail if issues found
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
